name: "Infrastructure AWS"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./tf

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: github_personal_oidc
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.9"

      - name: Terraform Init
        run: terraform init -upgrade -input=false -backend-config=key="$BACKEND_ACCESS_KEY" -backend-config=bucket="$BACKEND_STORAGE_ACCOUNT_NAME" -backend-config=region="$BACKEND_REGION"
        env:
          BACKEND_REGION: ${{ env.AWS_REGION }}
          BACKEND_STORAGE_ACCOUNT_NAME: pagincterraform
          BACKEND_ACCESS_KEY: paginc.tfstate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false -out pag.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve pag.tfplan

      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve